/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#define _vo volatile
//PERIPHERAL MEMORY MAP
#define APB1PERIPH_BASEADDR               0x40000000U
#define APB2PERIPH_BASEADDR               0x40010000U
#define AHB1PERIPH_BASEADDR               0x40020000U
#define AHB2PERIPH_BASEADDR               0x50000000U
//PERIPHERAL HANG ON BUS AHB1
#define RCC_BASEADDR                      0x40023800U
#define GPIOD_BASEADDR                    0x40020C00U
#define GPIOA_BASEADDR                    0x40020000U
//struct clock - RCC
typedef struct{
		_vo uint32_t CR;
		_vo uint32_t PLLCFGR;
		_vo uint32_t CFGR;
		_vo uint32_t CIR;
		_vo uint32_t AHB1RSTR;
		_vo uint32_t AHB2RSTR;
		uint32_t RESERVED1[2];
		_vo uint32_t APB1RSTR;
		_vo uint32_t APB2RSTR;
		uint32_t RESERVED2[2];
		_vo uint32_t AHB1ENR;
		_vo uint32_t AHB2ENR;
		uint32_t RESERVED3[2];
		_vo uint32_t APB1ENR;
		_vo uint32_t APB2ENR;
		uint32_t RESERVED4[2];
		_vo uint32_t AHB1LPENR;
		_vo uint32_t AHB2LPENR;
		uint32_t RESERVED5[2];
		_vo uint32_t APB1LPENR;
		_vo uint32_t APB2LPENR;
		uint32_t RESERVED6[2];
		_vo uint32_t BDCR;
		_vo uint32_t CSR;
		uint32_t RESERVED7[2];
		_vo uint32_t SSCGR;
		_vo uint32_t PLLI2SCFGR;
		uint32_t RESERVED8;
		_vo uint32_t DCKCFGR;
}RCC_RegDef_t;
#define RCC               ((RCC_RegDef_t*)RCC_BASEADDR)
//define  struct of GPIO
typedef struct
{
	_vo uint32_t MODER;
	_vo uint32_t OTYPER;
	_vo uint32_t OSPEEDR;
	_vo uint32_t PUPDR;
	_vo uint32_t IDR;
	_vo uint32_t ODR;
	_vo uint32_t BSRR;
	_vo uint32_t LCKR;
	_vo uint32_t AFR[2];
}GPIO_RegDef_t;
#define GPIOD               ((GPIO_RegDef_t*)GPIOD_BASEADDR)
#define GPIOA               ((GPIO_RegDef_t*)GPIOA_BASEADDR)
// GPIO_OUT
/*******STEPS TO FOLLOW***********
 *1. Enable GPIOD clock ,LED:PD12
 *2. Set the PIN PA0 as input
 *3. Configure the output mode i.e state,speed,pull,
 *********************************/
void Delay (uint32_t time)
{
	while (time--);
}
void myClock(){
	RCC->CR |= (1 << 0); //HSI ON
	//clock Port D,A
	RCC->AHB1ENR |= (1 << 0)|(1 << 3);
}
void myLed(){
	myClock();
	//mode:output, pushpull, fast,no pullup-pulldown
	GPIOD->MODER |= (1 << 24);
	GPIOD->OTYPER &= ~(1 << 12);
	GPIOD->OSPEEDR |= (2 << 24);
	GPIOD->PUPDR &= ~(1 << 24);//reset
}
void myButton(){
	myClock();
	//input,pull up:always be High. When the button is pressed,the current from PA0 will sink into the ground,and the pin will low
	GPIOA->MODER &= ~(1 << 0);//reset
	GPIOA->PUPDR |= (1 << 0);
}
int main(void)
{
	int count = 0;
	myClock();
	myLed();
	while(1){
	   if(!(GPIOA->IDR & (1 << 0))){
		   while(!(GPIOA->IDR & (1 << 0)));
		   GPIOD->ODR ^= (1 << 12);
		   count++;
	   }
	}
}
