/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define _vo volatile
#define PERIPH_BASEADDR                      0x40000000U
#define APB1PERIPH_BASEADDR                  PERIPH_BASEADDR
#define APB2PERIPH_BASEADDR                  0x40010000U
#define AHB1PERIPH_BASEADDR                  0x40020000U
#define AHB2PERIPH_BASEADDR                  0x50000000U

#define GPIOA                                (AHB1PERIPH_BASEADDR + 0x0000)
#define GPIOD                                (AHB1PERIPH_BASEADDR + 0x0C00)
#define RCC_BASEADDR                         (AHB1PERIPH_BASEADDR + 0x3800)

typedef struct
{
	_vo uint32_t CR;
	uint32_t RV1[11];
	_vo uint32_t AHB1ENR;
	_vo uint32_t AHB2ENR;
	uint32_t RV2[2];
	_vo uint32_t APB1ENR;
	_vo uint32_t APB2ENR;
}RCC_RegDef_t;
typedef struct
{
	_vo uint32_t MODER;
	_vo uint32_t OTYPER;
	_vo uint32_t OSPEEDR;
	_vo uint32_t PUPDR;
	_vo uint32_t IDR;
	_vo uint32_t ODR;
}GPIO_RegDef_t;
#define RCC                               ((RCC_RegDef_t*)RCC_BASEADDR)
#define PA                                ((GPIO_RegDef_t*)GPIOA)
#define PD                                ((GPIO_RegDef_t*)GPIOD)
void delay(void){
	for(int i=0;i<500000; i++);
}
void Clock_init(void)
{
    RCC->CR |= (1 << 0);
    RCC->AHB1ENR |= (1 << 3);                     // (1 << 0)|(1 << 3);
}
int main(void)
{

	//port-pin-out-fast-pp
	//clock
	Clock_init();
    //config led
    PD->MODER |= (1 << 26);    //pin 13
    PD->OTYPER &= ~(1 << 13) ; //reset state~push-pull
    PD->OSPEEDR |= (1 << 26);  //medium Speed   // PD->ODR |= (1 << 13);

	while(1){
		delay();
	    PD->ODR ^= (1 << 13);
	}
	return 0;
}
